version: '3.8'
services:
  seller:
    build:
      context: ./seller-service
      dockerfile: Dockerfile
    container_name: seller
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
      - /app/seller/node_modules
  
  buyer:
    build:
      context: ./buyer-service
      dockerfile: Dockerfile
    container_name: buyer
    ports:
      - "5001:5001"
    restart: always
    volumes:
      - .:/app
      - /app/buyer/node_modules
  
  admin:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "5002:5002"
    restart: always
    volumes:
      - .:/app
      - /app/admin/node_modules
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
        - "80:80"
    depends_on:
      - seller
      - buyer
      - admin