version: '3.8'
services:
  seller:
    build:
      dockerfile: Dockerfile
      context: ./seller
    container_name: seller
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
      - /app/seller/node_modules
  
  buyer:
    build:
      dockerfile: Dockerfile
      context: ./buyer
    container_name: buyer
    ports:
      - "5001:5001"
    restart: always
    volumes:
      -.:/app
      - /app/buyer/node_modules
  
  admin:
    build:
      dockerfile: Dockerfile
      context: ./admin
    container_name: admin
    ports:
      - "5002:5002"
    restart: always
    volumes:
      - .:/app
      - /app/admin/node_modules
  
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
      depends_on:
        - seller
        - buyer
        - admin
      ports:
        - "80:80"