POST http://localhost:5003/login

###
POST http://localhost:5001/buyer/buyer-reg
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDQ5OTQwNDgsImV4cCI6MTY0NDk5NDEwOH0.t1XM4fYng2XBNOiAvDarXz7OMWJg9ZdmG8pMazeKpgPNSEG0u0lCU_UGW5B3bp-IKB3luD_vMMhIpHV8kdtNSOViY48ekKi1kE7fI8co7omWfRHGhIcKc5QcqfAPhYVccnHzec4I8t6JT8_XkvJUM6NgWnX43aRYwhdy4Dy7cRkjC-43tNmVqnKriANJA6wPN0zJpcBXEFSev99qiJzYx1-uVwGCyXyUXpp5N819mPVj2d5HXRiboMVQtHojlG261rkB099DhKbfDvmptBD63LpLSPu7tHNb5xq-FD40rWgh5LkTRHX-RHOZ6JP2SX6k5tnRoUsHwhlKiobXUWqf3zXH7iSTQTXOlDiASdYdmHo1gqOlSBIyFtYm_6RqKEDf9Qf-rIksXM51Os41b1H3boispeADPTKPeE1JqRMMWoycfEeNo-lPByXKVMsT1gLEZXTVCurHPchjkOACsIq3IrySgED02UxKb0GIqMjMm5v6kgWnIYP6fTG_72DBBUS0
###
GET http://localhost:5001/buyer/get-buyer